In [23]:
#Import main lib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import seaborn as sns
import json

In [ ]:
# Main dataset link(you can download from here)

#https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata (just choose credit dataset)

In [24]:
#Display max dataframe
pd.set_option('display.max_columns', None)

In [25]:
# Set visualization defaults
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

In [27]:
#Import 2 dataset

df_credit = pd.read_csv("/content/tmdb_5000_credits.csv")
df_movie = pd.read_csv("/content/Last_movie_dataset (2).csv")

In [28]:
df_credit.head(5)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [29]:
df_movie.head(5)

,Unnamed: 0,budget,homepage,id,original_language,original_title,overview,popularity,release_date,revenue,runtime,status,tagline,title,vote_average,vote_count,genres_list,genres_count,genres_unique,new_keys,companies,country,language,year,profit,roi
0,0,237000000,http://www.avatarmovie.com/,19995,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,2009-12-10,237000000,162.0,Released,Enter the World of Pandora.,Avatar,7.2,11800,"['Action', 'Adventure', 'Fantasy', 'Science Fi...",4,Action,"['culture clash', 'future', 'space war', 'spac...","['Ingenious Film Partners', 'Twentieth Century...","['United States of America', 'United Kingdom']","['en', 'es']",2009.0,237000000,100.0
1,1,300000000,http://disney.go.com/disneypictures/pirates/,285,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,2007-05-19,300000000,169.0,Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"['Adventure', 'Fantasy', 'Action']",3,Adventure,[],"['Walt Disney Pictures', 'Jerry Bruckheimer Fi...",['United States of America'],['en'],2007.0,300000000,100.0
2,2,245000000,http://www.sonypictures.com/movies/spectre/,206647,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,2015-10-26,245000000,148.0,Released,A Plan No One Escapes,Spectre,6.3,4466,"['Action', 'Adventure', 'Crime']",3,Action,"['spy', 'based on novel', 'secret agent', 'seq...","['Columbia Pictures', 'Danjaq', 'B24']","['United Kingdom', 'United States of America']","['fr', 'en', 'es', 'it', 'de']",2015.0,245000000,100.0
3,3,250000000,http://www.thedarkknightrises.com/,49026,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,2012-07-16,250000000,165.0,Released,The Legend Ends,The Dark Knight Rises,7.6,9106,"['Action', 'Crime', 'Drama', 'Thriller']",4,Action,"['dc comics', 'crime fighter', 'terrorist', 's...","['Legendary Pictures', 'Warner Bros.', 'DC Ent...",['United States of America'],['en'],2012.0,250000000,100.0
4,4,260000000,http://movies.disney.com/john-carter,49529,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,2012-03-07,260000000,132.0,Released,"Lost in our world, found in another.",John Carter,6.1,2124,"['Action', 'Adventure', 'Science Fiction']",3,Action,"['based on novel', 'mars', 'medallion', 'space...",['Walt Disney Pictures'],['United States of America'],['en'],2012.0,260000000,100.0

#Just focus credit dataset because Movie dataset is already clean and preprocessing:(You can access here for movie dataset preprocessing)
--------------------------------------------
[https://github.com/KananQasimzada10/Movie-Analysis](https://): Preprocessing and analysis of Movies dataset

In [30]:
# 1.1Function to extract the first cast member's gender, name, and character

def extract_first_cast_info(cast_data):
    cast_list = json.loads(cast_data)  #
    if cast_list:
        first_cast_member = cast_list[0]
        gender = 'Male' if first_cast_member.get('gender') == 2 else 'Female' if first_cast_member.get('gender') == 1 else 'Other'
        return first_cast_member.get('name'), first_cast_member.get('character'), gender
    return None, None, None

# 1.2Function to extract the first crew member's department, job, and name
def extract_first_crew_info(crew_data):
    crew_list = json.loads(crew_data)
    if crew_list:
        first_crew_member = crew_list[0]
        gender = 'Male' if first_crew_member.get('gender') == 2 else 'Female' if first_crew_member.get('gender') == 1 else 'Other'

        return first_crew_member.get('name'), first_crew_member.get('department'), first_crew_member.get('job'), gender
    return None, None, None


df_credit[['actor_name', 'character_name', 'cast_gender']] = df_credit['cast'].apply(lambda x: pd.Series(extract_first_cast_info(x)))
df_credit[['director_name', 'department', 'job_name', 'crew_gender']] = df_credit['crew'].apply(lambda x: pd.Series(extract_first_crew_info(x)))

important_columns = df_credit[['movie_id', 'title', 'actor_name', 'character_name', 'cast_gender',
                             'director_name', 'department', 'job_name', 'crew_gender']]

important_columns.head()

,movie_id,title,actor_name,character_name,cast_gender,director_name,department,job_name,crew_gender
0,19995,Avatar,Sam Worthington,Jake Sully,Male,Stephen E. Rivkin,Editing,Editor,Other
1,285,Pirates of the Caribbean: At World's End,Johnny Depp,Captain Jack Sparrow,Male,Dariusz Wolski,Camera,Director of Photography,Male
2,206647,Spectre,Daniel Craig,James Bond,Male,Thomas Newman,Sound,Original Music Composer,Male
3,49026,The Dark Knight Rises,Christian Bale,Bruce Wayne / Batman,Male,Hans Zimmer,Sound,Original Music Composer,Male
4,49529,John Carter,Taylor Kitsch,John Carter,Male,Andrew Stanton,Writing,Screenplay,Male

In [31]:
print(df_credit.shape)
print(df_movie.shape)

(4803, 11)
(3766, 26)

In [32]:
#Joined 2 main dataset for analysis

joined_df = df_credit.join(df_movie.set_index('id'), on='movie_id', how='inner', lsuffix='_credits', rsuffix='_movies')
joined_df.head(5)

,movie_id,title_credits,cast,crew,actor_name,character_name,cast_gender,director_name,department,job_name,crew_gender,Unnamed: 0,budget,homepage,original_language,original_title,overview,popularity,release_date,revenue,runtime,status,tagline,title_movies,vote_average,vote_count,genres_list,genres_count,genres_unique,new_keys,companies,country,language,year,profit,roi
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",Sam Worthington,Jake Sully,Male,Stephen E. Rivkin,Editing,Editor,Other,0,237000000,http://www.avatarmovie.com/,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,2009-12-10,237000000,162.0,Released,Enter the World of Pandora.,Avatar,7.2,11800,"['Action', 'Adventure', 'Fantasy', 'Science Fi...",4,Action,"['culture clash', 'future', 'space war', 'spac...","['Ingenious Film Partners', 'Twentieth Century...","['United States of America', 'United Kingdom']","['en', 'es']",2009.0,237000000,100.0
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",Johnny Depp,Captain Jack Sparrow,Male,Dariusz Wolski,Camera,Director of Photography,Male,1,300000000,http://disney.go.com/disneypictures/pirates/,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,2007-05-19,300000000,169.0,Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"['Adventure', 'Fantasy', 'Action']",3,Adventure,[],"['Walt Disney Pictures', 'Jerry Bruckheimer Fi...",['United States of America'],['en'],2007.0,300000000,100.0
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",Daniel Craig,James Bond,Male,Thomas Newman,Sound,Original Music Composer,Male,2,245000000,http://www.sonypictures.com/movies/spectre/,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,2015-10-26,245000000,148.0,Released,A Plan No One Escapes,Spectre,6.3,4466,"['Action', 'Adventure', 'Crime']",3,Action,"['spy', 'based on novel', 'secret agent', 'seq...","['Columbia Pictures', 'Danjaq', 'B24']","['United Kingdom', 'United States of America']","['fr', 'en', 'es', 'it', 'de']",2015.0,245000000,100.0
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Christian Bale,Bruce Wayne / Batman,Male,Hans Zimmer,Sound,Original Music Composer,Male,3,250000000,http://www.thedarkknightrises.com/,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,2012-07-16,250000000,165.0,Released,The Legend Ends,The Dark Knight Rises,7.6,9106,"['Action', 'Crime', 'Drama', 'Thriller']",4,Action,"['dc comics', 'crime fighter', 'terrorist', 's...","['Legendary Pictures', 'Warner Bros.', 'DC Ent...",['United States of America'],['en'],2012.0,250000000,100.0
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",Taylor Kitsch,John Carter,Male,Andrew Stanton,Writing,Screenplay,Male,4,260000000,http://movies.disney.com/john-carter,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,2012-03-07,260000000,132.0,Released,"Lost in our world, found in another.",John Carter,6.1,2124,"['Action', 'Adventure', 'Science Fiction']",3,Action,"['based on novel', 'mars', 'medallion', 'space...",['Walt Disney Pictures'],['United States of America'],['en'],2012.0,260000000,100.0

In [33]:
joined_df.shape

(3766, 36)

In [36]:
actor_profit = joined_df.groupby('actor_name')['profit'].sum()
actor_profit_10 = actor_profit.nlargest(10)
actor_profit_10

actor_name
Johnny Depp          2626500000
Tom Cruise           2000000000
Bruce Willis         1841300000
Tom Hanks            1686000000
Nicolas Cage         1628820000
Will Smith           1621100000
Ben Stiller          1592000000
Adam Sandler         1515700000
Matt Damon           1406200000
Robert Downey Jr.    1396000000
Name: profit, dtype: int64

In [37]:
fig = px.bar(
    x=actor_profit_10.index,
    y=actor_profit_10.values,
    title='Top10 profit actor',
    labels={'x':'Actors', 'y': 'Profit'},
    color=actor_profit_10.values,
    color_continuous_scale='viridis'
)

fig.update_layout(showlegend=False)
fig.show()

In [38]:
director_top10 = joined_df.groupby('director_name')['profit'].sum()
director_top10 = director_top10.nlargest(10)
director_top10

director_name
Hans Zimmer       3631500000
Alan Silvestri    3298000000
Avy Kaufman       2570500000
Debra Zane        2268250000
John Williams     2220500025
Lucinda Syson     2119000000
Ronna Kress       1803000000
Andrew Stanton    1789000000
Danny Elfman      1755000000
Denise Chamian    1639700003
Name: profit, dtype: int64

In [39]:
fig = px.bar(
    x=director_top10.index,
    y=director_top10.values,
    title='Top 10 Director',
    labels={'x':'Director', 'y':'Profit'},
    color=director_top10.values,
    color_continuous_scale='viridis'
)
fig.update_layout(showlegend=False)
fig.show()

In [42]:
joined_df.columns

Index(['movie_id', 'title_credits', 'cast', 'crew', 'actor_name',
       'character_name', 'cast_gender', 'director_name', 'department',
       'job_name', 'crew_gender', 'Unnamed: 0', 'budget', 'homepage',
       'original_language', 'original_title', 'overview', 'popularity',
       'release_date', 'revenue', 'runtime', 'status', 'tagline',
       'title_movies', 'vote_average', 'vote_count', 'genres_list',
       'genres_count', 'genres_unique', 'new_keys', 'companies', 'country',
       'language', 'year', 'profit', 'roi'],
      dtype='object')

In [43]:
#Select last 30 years most popular actors

last_30 = joined_df[joined_df['year'] >= 1990]

popular_actors_last30 = last_30.groupby(['year', 'actor_name'])['vote_average'].mean()
popular_actors_last30 = popular_actors_last30.nlargest(10)
popular_actors_last30

year    actor_name
1994.0  Dermot Mulroney    8.5
1993.0  Liam Neeson        8.3
1994.0  John Travolta      8.3
1999.0  Edward Norton      8.3
2001.0  Rumi Hiiragi       8.3
2014.0  Miles Teller       8.3
1990.0  Robert De Niro     8.2
1994.0  Tom Hanks          8.2
1997.0  Yōji Matsuda       8.2
1998.0  Edward Norton      8.2
Name: vote_average, dtype: float64

In [48]:
popular_actors_years_10_df = popular_actors_last30.reset_index()

fig = px.line(
    popular_actors_years_10_df,
    x='actor_name',
    y='year',
    title='Top 10 rating Actor since 1990',
    markers=True,
    hover_data={'actor_name': False, 'year': True, 'vote_average': True}  # Display year and rating on hover

)

fig.update_traces(line_color='#1f77b4', line_width=3)
fig.update_layout(hovermode='x unified')
fig.show()

In [50]:
popular_director_years_10 = last_30.groupby(['year', 'director_name'])['vote_average'].mean()
popular_director_years_10 = popular_director_years_10.nlargest(10).reset_index()
popular_director_years_10

     year      director_name  vote_average
0  1994.0    Lynn Stalmaster           8.5
1  1994.0  Quentin Tarantino           8.3
2  1999.0      Arnon Milchan           8.3
3  2001.0      John Lasseter           8.3
4  2015.0          Jem Cohen           8.3
5  1990.0    Martin Scorsese           8.2
6  1997.0     Hayao Miyazaki           8.2
7  1998.0        Steve Tisch           8.2
8  2003.0     John Goldsmith           8.2
9  1991.0       Howard Shore           8.1

In [52]:
fig = px.line(
    popular_director_years_10,
    x='director_name',
    y='year',
    title='Top 10 rating Director since 1990',
    markers=True,
    hover_data={'director_name': False, 'year': True, 'vote_average': True}  # Display year and rating on hover

)

fig.update_traces(line_color='#1f77b4', line_width=3)
fig.update_layout(hovermode='x unified')
fig.show()

In [54]:
actor_profit_5 = last_30.groupby(['actor_name', 'year'])['profit'].sum()
actor_profit_5 = actor_profit_5.nlargest(5)
actor_profit_5

actor_name     year
Johnny Depp    2011.0    515000000
Taylor Kitsch  2012.0    469000000
Hugh Jackman   2006.0    434000000
Dennis Quaid   2004.0    315000000
Owen Wilson    2011.0    307000000
Name: profit, dtype: int64

In [59]:
actor_profit_5_df = actor_profit_5.reset_index()

fig = px.line(
    actor_profit_5_df,
    x='year',  # x-axis is the year
    y='profit',  # y-axis is the profit
    color='actor_name',  # Color lines by actor
    markers=True,  # Add markers on the lines
    title='Top 5 Actors by Total Profit Over Years'
)

fig.update_layout(
    xaxis_title='Year',
    yaxis_title='Profit',
    hovermode='x unified'  # Show tooltip for each actor when hovering
)

fig.show()